/**
 * README template for Math Brain chart data exports
 * This explains what the download contains and how to use it
 */

export const generateDownloadReadme = (params: {
  reportType: 'solo_mirror' | 'solo_balance_meter' | 'relational_mirror' | 'relational_balance_meter';
  personA: string;
  personB?: string;
  exportDate: Date;
  includesTransits: boolean;
}) => {
  const reportLabel = {
    solo_mirror: 'Solo Mirror (Natal Chart)',
    solo_balance_meter: 'Solo Balance Meter (Natal + Transits)',
    relational_mirror: 'Relational Mirror (Synastry)',
    relational_balance_meter: 'Relational Balance Meter (Synastry + Transits)'
  }[params.reportType];

  return `═══════════════════════════════════════════════════════════════
 RAVEN CALDER CHART DATA EXPORT
 Woven Web Application • Math Brain
═══════════════════════════════════════════════════════════════

📋 WHAT IS THIS?

This download contains symbolic chart data for AI-assisted analysis.
It is NOT meant to be read like a book or traditional report.

Think of this as "raw ingredients" for an AI instance to interpret,
rather than a finished reading for humans.

═══════════════════════════════════════════════════════════════

📦 CONTENTS

Your download includes:

1. PDF File with ANALYSIS DIRECTIVE
   • Chart data (planetary positions, aspects, houses)
   • System instructions for Raven Calder methodology
   • Symbolic framework and interpretation protocol
   ${params.includesTransits ? '• Transit data and seismograph indices' : ''}

2. JSON File (Frontstage Data)
   • Machine-readable chart geometry
   • Normalized values for AI processing
   • Full data tables and calculations

${params.includesTransits ? `3. Graphs PDF (if Balance Meter)
   • Visual charts showing transit patterns
   • Seismograph visualizations
   • Climate trend graphs
` : ''}
═══════════════════════════════════════════════════════════════

🤖 HOW TO USE THIS DATA

These files are designed for:

✅ Perplexity API (Woven Web App)
   The in-app Poetic Brain uses Perplexity for narrative generation

✅ Custom GPT (ChatGPT)
   Upload the PDF to create a custom Raven Calder instance

✅ Custom GPT (ChatGPT)
   Upload the PDF to provide chart context for analysis

✅ Claude Projects
   Add the PDF as project knowledge for symbolic analysis

═══════════════════════════════════════════════════════════════

⚠️  IMPORTANT NOTES

• The PDF starts with "YOU ARE RAVEN CALDER — EXECUTE THIS DIRECTIVE"
  This commands the AI to act as Raven Calder immediately and generate
  a reading following the specific structure: SOLO MIRROR → RELATIONAL
  ENGINES → WEATHER OVERLAY (not just describe the data).

• The JSON contains raw calculations and is not human-readable.
  It's meant for programmatic analysis or advanced debugging.

• This is NOT traditional astrology. It follows the Woven Map
  framework: FIELD → MAP → VOICE (symbolic diagnostics, not fate).

• The reading structure emphasizes:
  - MIRROR (conversational reflection, not prescription)
  - CONVERSATION STARTER (opening dialogue, not final verdict)
  - Plain language, falsifiable claims, agency-first framing

• The AI will generate interpretations based on this data. You
  remain the validator — decide what resonates and what doesn't.

═══════════════════════════════════════════════════════════════

📊 REPORT DETAILS

Report Type: ${reportLabel}
Person A: ${params.personA}
${params.personB ? `Person B: ${params.personB}` : ''}
Export Date: ${params.exportDate.toISOString()}
Includes Transits: ${params.includesTransits ? 'Yes' : 'No'}

═══════════════════════════════════════════════════════════════

🔗 NEED HELP?

Visit https://github.com/anthropics/claude-code/issues
Or return to the Woven Web App at https://wovenweb.app

═══════════════════════════════════════════════════════════════

Generated by Raven Calder • Woven Web Application
Symbolic weather, not deterministic prediction.
`;
};
